apiVersion: apps/v1
kind: Deployment

metadata:
  name: server-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
        role: rolling-update
    spec:
      # hostNetwork: true
      restartPolicy: Always
      containers:
        - name: server-container
          image: localhost:5000/labosdiscordbot-server
          imagePullPolicy: Never
          env:
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: DISCORD_BOT_TOKEN
            - name: DISCORD_BOT_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: DISCORD_BOT_CLIENT_ID
            - name: DISCORD_BOT_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: server-configmap
                  key: DISCORD_BOT_CLIENT_SECRET
          ports:
            - containerPort: 8080
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            # tcpSocket:
            #   port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
