apiVersion: v1
kind: ConfigMap

metadata:
  name: server-configmap

data:
  DISCORD_BOT_TOKEN: "$(DISCORD_BOT_TOKEN)"
  DISCORD_BOT_CLIENT_ID: "$(DISCORD_BOT_CLIENT_ID)"
  DISCORD_BOT_CLIENT_SECRET: "$(DISCORD_BOT_CLIENT_SECRET)"
