apiVersion: apps/v1
kind: Deployment

metadata:
  name: client

spec:
  replicas: 10
  selector:
    matchLabels:
      app: labos-discord-bot
      tier: client
  template:
    metadata:
      labels:
        app: labos-discord-bot
        tier: client
        role: rolling-update
    spec:
      restartPolicy: Always
      containers:
        - name: client-container
          image: localhost:5000/labosdiscordbot:client
          imagePullPolicy: Never
          env:
            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: THIS_STRING_IS_REPLACED_DURING_BUILD
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 30

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 2
