version: '3'

services:
    jenkins:
        build: .
        network_mode: "host"
        environment:
            JENKINS_USER_PASSWORD: admin
            GIT_REPOSITORY_URL: vincent-andrieu/LabosDiscordBotV2
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        depends_on:
            - docker-registry
        restart: always

    docker-registry:
        image: registry:2.7.1
        ports:
            - "5000:5000"
        restart: always