version: '3'

services:
    client:
        build: ./client
        ports:
            - "80:80"
        restart: always

    server:
        build: ./server
        environment:
            DISCORD_BOT_TOKEN: ''
        network_mode: "host"
        depends_on:
            - db
        restart: always

    db:
        image: mongo:4.4
        volumes:
            - mongodb-data:/data/db
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: DiscordLaboBotV2
        restart: always

volumes:
    mongodb-data: