version: '3'

services:
    jenkins:
        build: .
        environment:
            JENKINS_USER_PASSWORD: admin
            GIT_REPOSITORY_URL: vincent-andrieu/LabosDiscordBotV2
        ports:
            - "4242:4242"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        depends_on:
            - docker-registry
        restart: always

    docker-registry:
        image: registry:2.7.1
        expose:
            - 5000
        restart: always