name: Check compilation

on:
  push:
    branches:
      - master

jobs:
  client:
    container: mongo:4.4
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Run
      - name: Run compilation
        working-directory: client
        run: npm run deploy

  server:
    container: mongo:4.4
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Run
      - name: Run compilation
        working-directory: server
        run: npm run deploy