name: Check compilation

on:
  push:
    branches:
      - master

jobs:
  client:
    runs-on: ubuntu-20.04
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Run
      - name: Run compilation
        run: npm i && npm run deploy --prefix client

  server:
    runs-on: ubuntu-20.04
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Run
      - name: Run compilation
        run: npm i && npm run deploy --prefix server