name: Check compilation

on:
  push:
    branches:
      - master

jobs:
  client:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        mongodb-version: ['4.4.0']
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      # Run
      - name: Run compilation
        working-directory: client
        run: npm run deploy

  server:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        mongodb-version: ['4.4.0']
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      # Run
      - name: Run compilation
        working-directory: server
        run: npm run deploy